import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant';
import type { NavigationTree } from '@/@types/navigation';
import { ADMIN, DUENIO, ENTRENADOR, DISPOSITIVO } from '@/constants/roles.constant';

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: '🏠 Inicio',
        translateKey: 'nav.home',
        icon: 'HiOutlineHome',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'transmitir',
        path: '/transmision-dispositivo',
        title: 'Transmitir',
        translateKey: 'nav.transmitir',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [DISPOSITIVO],
        subMenu: [],
        
    },
    {
        key: 'categorias',
        path: '/categorias',
        title: '📂 Categorías',
        translateKey: 'nav.categorias',
        icon: 'HiOutlineFolder',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, DUENIO, ENTRENADOR],
        subMenu: [
            {
                key: 'categorias-ejercicios',
                path: '/categorias-ejercicios',
                title: '📂 Categorías de Ejercicios',
                translateKey: 'nav.categoriasEjercicios',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
        ],
    },
    {
        key: 'ejercicios',
        path: '/ejercicios',
        title: '🏋️ Ejercicios',
        translateKey: 'nav.ejercicios',
        icon: 'HiOutlineClipboardList',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, DUENIO, ENTRENADOR],
        subMenu: [
            {
                key: 'listado-ejercicios',
                path: '/ejercicios/listado',
                title: '📋 Listado de Ejercicios',
                translateKey: 'nav.listadoEjercicios',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
            {
                key: 'nuevo-ejercicio',
                path: '/ejercicios/nuevo',
                title: '➕ Nuevo Ejercicio',
                translateKey: 'nav.nuevoEjercicio',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
        ],
    },
    {
        key: 'bloquesEjercicios',
        path: '/bloques',
        title: '🧩 Bloques de Ejercicios',
        translateKey: 'nav.bloquesEjercicios',
        icon: 'HiOutlineCollection',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, DUENIO, ENTRENADOR],
        subMenu: [
            {
                key: 'listado-bloques',
                path: '/bloques/listado',
                title: '📋 Listado de Bloques',
                translateKey: 'nav.listadoBloques',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
            {
                key: 'nuevo-bloque',
                path: '/bloques/nuevo',
                title: '➕ Nuevo Bloque',
                translateKey: 'nav.nuevoBloque',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
        ],
    },
    {
        key: 'rutinas',
        path: '/rutinas',
        title: '📆 Rutinas',
        translateKey: 'nav.rutinas',
        icon: 'HiOutlineCalendar',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, ENTRENADOR, DUENIO],
        subMenu: [
            {
                key: 'listado-rutinas',
                path: '/rutinas/listado',
                title: '📋 Listado de Rutinas',
                translateKey: 'nav.listadoRutinas',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, ENTRENADOR, DUENIO],
                subMenu: [],
            },
            {
                key: 'nueva-rutina',
                path: '/rutinas/nueva',
                title: '➕ Nueva Rutina',
                translateKey: 'nav.nuevaRutina',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, ENTRENADOR, DUENIO],
                subMenu: [],
            },
        ],
    },
    {
        key: 'dispositivos',
        path: '/dispositivos',
        title: '📺 Dispositivos',
        translateKey: 'nav.dispositivos',
        icon: 'HiOutlineDeviceMobile',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, DUENIO, ENTRENADOR],
        subMenu: [],
    },
    {
        key: 'clases',
        path: '/clases',
        title: '📅 Clases',
        translateKey: 'nav.clases',
        icon: 'HiOutlineCalendar',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, DUENIO, ENTRENADOR],
        subMenu: [
            {
                key: 'listado-clases',
                path: '/clases/listado',
                title: '📋 Listado de Clases',
                translateKey: 'nav.listadoClases',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
            {
                key: 'nueva-clase',
                path: '/clases/nueva',
                title: '➕ Nueva Clase',
                translateKey: 'nav.nuevaClase',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
        ],
    },
    {   
        
            key: 'tipo-clases',
            path: '/clases/tipo',
            title: '🗂 Tipo de Clases',
            translateKey: 'nav.tipoClases',
            icon: 'HiOutlineCollection',
            type: NAV_ITEM_TYPE_COLLAPSE,
            authority: [ADMIN, DUENIO, ENTRENADOR],
            subMenu: [
                {
                    key: 'listado-tipos-clases',
                    path: '/clases/tipo/listado',
                    title: '📋 Listado de Tipos de Clases',
                    translateKey: 'nav.listadoTiposClases',
                    icon: '',
                    type: NAV_ITEM_TYPE_ITEM,
                    authority: [ADMIN, DUENIO, ENTRENADOR],
                    subMenu: [],
                },
                {
                    key: 'agregar-tipo-clase',
                    path: '/clases/tipo/nuevo',
                    title: '➕ Agregar Tipo de Clase',
                    translateKey: 'nav.agregarTipoClase',
                    icon: '',
                    type: NAV_ITEM_TYPE_ITEM,
                    authority: [ADMIN, DUENIO, ENTRENADOR],
                    subMenu: [],
                },
            ],
        },    
];

export default navigationConfig;
