import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant';
import type { NavigationTree } from '@/@types/navigation';
import { ADMIN, DUENIO, ENTRENADOR } from '@/constants/roles.constant';

const navigationConfig: NavigationTree[] = [
    {
        key: 'Panel de control',
        path: '/home',
        title: '🏠 Home',
        translateKey: 'nav.home',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    // {
    //     key: 'ajustes',
    //     path: '/ajustes',
    //     title: 'Ajustes',
    //     translateKey: 'nav.ajustes',
    //     icon: 'ajustes',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [ADMIN, DUENIO],
    //     subMenu: [
    //         {
    //             key: 'tiposDeClases',
    //             path: '/ajustes/tipos-de-clases',
    //             title: 'Tipos de Clases',
    //             translateKey: 'nav.tiposDeClases',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [ADMIN, DUENIO],
    //             subMenu: [],
    //         },
    //     ],
    // },
    {
        key: 'categoriaEjercicios',
        path: '/categorias-ejercicios',
        title: '📂Categoría de Ejercicios',
        translateKey: 'nav.categoriasEjercicios',
        icon: '',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, DUENIO],
        subMenu: [],
    },
    // {
    //     key: 'musculos',
    //     path: '/musculos',
    //     title: 'Músculos',
    //     translateKey: 'nav.musculos',
    //     icon: 'musculos',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    {
        key: 'ejercicios',
        path: '/ejercicios',
        title: '🏋️ Ejercicios',
        translateKey: 'nav.ejercicios',
        icon: 'exercise',
        type: NAV_ITEM_TYPE_COLLAPSE, // Cambiado a COLLAPSE para incluir submenús
        authority: [ADMIN, DUENIO],
        subMenu: [
            {
                key: 'listado-ejercicios',
                path: '/ejercicios/listado',
                title: '📋 Listado de Ejercicios',
                translateKey: 'nav.listadoEjercicios',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO],
                subMenu: [],
            },
            {
                key: 'nuevo-ejercicio',
                path: '/ejercicios/nuevo',
                title: '➕ Nuevo Ejercicio',
                translateKey: 'nav.nuevoEjercicio',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO],
                subMenu: [],
            },
        ],
    },
    {
        key: 'bloquesEjercicios',
        path: '/bloques',
        title: 'Bloques',
        translateKey: 'nav.bloquesEjercicios',
        icon: 'bloques',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, DUENIO, ENTRENADOR],
        subMenu: [
            {
                key: 'listado-bloques',
                path: '/bloques',
                title: '📋 Listado de Bloques',
                translateKey: 'nav.listadoBloques',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
            {
                key: 'nuevo-bloque',
                path: '/bloques/nuevo',
                title: '➕ Nuevo Bloque',
                translateKey: 'nav.nuevoBloque',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
        ],
    },
    {
        key: 'rutinas',
        path: '/rutinas',
        title: '📆 Rutinas',
        translateKey: 'nav.rutinas',
        icon: 'calendar',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, ENTRENADOR, DUENIO],
        subMenu: [
            {
                key: 'listado-rutinas',
                path: '/rutinas/listado',
                title: '📋 Listado de Rutinas',
                translateKey: 'nav.listadoRutinas',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, ENTRENADOR, DUENIO],
                subMenu: [],
            },
            {
                key: 'nueva-rutina',
                path: '/rutinas/nueva',
                title: '➕ Nueva Rutina',
                translateKey: 'nav.nuevaRutina',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, ENTRENADOR, DUENIO],
                subMenu: [],
            },
        ],
    },
    {
        key: 'dispositivos',
        path: '/dispositivos',
        title: '📺 Dispositivos',
        translateKey: 'nav.dispositivos',
        icon: 'exercise',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [DUENIO],
        subMenu: [],
    },
    {
        key: 'clases',
        path: '/clases',
        title: '📅 Clases',
        translateKey: 'nav.clases',
        icon: 'clases',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, DUENIO, ENTRENADOR],
        subMenu: [
            {
                key: 'listado-clases',
                path: '/clases/listado',
                title: '📋 Listado de Clases',
                translateKey: 'nav.listadoClases',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
            {
                key: 'nueva-clase',
                path: '/clases/nueva',
                title: '➕ Nueva Clase',
                translateKey: 'nav.nuevaClase',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, DUENIO, ENTRENADOR],
                subMenu: [],
            },
        ],
    }
];


export default navigationConfig;
